apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: ${JOB_NAME}
  labels:
    kueue.x-k8s.io/queue-name: hyperpod-ns-ag-mitra-localqueue
spec:
  elasticPolicy:
    rdzvBackend: c10d
    minReplicas: 1
    maxReplicas: 64
    maxRestarts: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 90
  pytorchReplicaSpecs:
    Worker:
      replicas: ${NNODES}
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            app: sft
            kueue.x-k8s.io/queue-name: hyperpod-ns-ag-mitra-localqueue
        spec:
          volumes:
            - name: shmem
              hostPath: 
                path: /dev/shm
            - name: local
              hostPath:
                path: /mnt/k8s-disks/0
            - name: fsx-storage
              persistentVolumeClaim:
                claimName: fsx-claim-mitra-prod
          nodeSelector:
           node.kubernetes.io/instance-type: "ml.p4d.24xlarge"
          containers:
            - name: pytorch
              image: ${IMAGE}
              imagePullPolicy: Always
              resources:
                requests:
                  nvidia.com/gpu: 8
                  vpc.amazonaws.com/efa: 4
                  cpu: 32
                  memory: 384Gi
                limits:
                  nvidia.com/gpu: 8
                  vpc.amazonaws.com/efa: 4
                  cpu: 32
                  memory: 384Gi
              env:
              - name: LOGLEVEL
                value: "DEBUG"
              - name: NNODES
                value: "${NNODES}"
              - name: BASE_MODEL
                value: "${BASE_MODEL}"
              - name: DATASET
                value: "${DATASET}"
              - name: EPOCHS
                value: "${EPOCHS}"
              - name: ALIAS
                value: "${ALIAS}"
              - name: EXTRA_TRAINER_ARGS
                value: "${EXTRA_TRAINER_ARGS}"
              command: ["/bin/sh"]
              args:
                - "-c"
                - >
                  ${COMMAND}
              volumeMounts:
                - name: shmem
                  mountPath: /dev/shm
                - name: local
                  mountPath: /local
                - name: fsx-storage
                  mountPath: /fsx
